# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import satellite_net_pb2 as satellite__net__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in satellite_net_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataLinkStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransferImage = channel.unary_unary(
                '/satellite.DataLink/TransferImage',
                request_serializer=satellite__net__pb2.ImageChunk.SerializeToString,
                response_deserializer=satellite__net__pb2.TransferAck.FromString,
                _registered_method=True)


class DataLinkServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TransferImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataLinkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransferImage': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferImage,
                    request_deserializer=satellite__net__pb2.ImageChunk.FromString,
                    response_serializer=satellite__net__pb2.TransferAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'satellite.DataLink', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('satellite.DataLink', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataLink(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TransferImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/satellite.DataLink/TransferImage',
            satellite__net__pb2.ImageChunk.SerializeToString,
            satellite__net__pb2.TransferAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
